import pandas as pd
from pathlib import Path


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = BASE_DIR / "data"

RAW_DIR = DATA_DIR / "raw"
CLEANED_DIR = DATA_DIR / "cleaned"

HISTORICAL_SEM2_DIR = CLEANED_DIR / "historical_sem2"

OUTPUT_DIR = DATA_DIR / "analysis" / "dashboard2"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# PERFORMANCE SETTINGS
# ============================================================

ASSIGNMENT_MAX_MARKS = 20
TEST_MAX_MARKS = 20

ATTENDANCE_WEIGHT = 0.30
ASSIGNMENT_WEIGHT = 0.30
TEST_WEIGHT = 0.40


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def find_cleaned_file(folder, base_name):
    """
    Finds cleaned CSV using the standard cleaning output name.

    Example:
        assignments.csv
        ->
        assignments_cleaned.csv
    """

    possible_names = [
        f"{base_name}_cleaned.csv",
        f"{base_name}.csv"
    ]

    for name in possible_names:

        path = folder / name

        if path.exists():
            return path

    return None


def load_cleaned_csv(folder, base_name, required=True):
    """
    Load a cleaned dataset.
    """

    path = find_cleaned_file(
        folder,
        base_name
    )

    if path is None:

        if required:

            raise FileNotFoundError(
                f"\nRequired file not found.\n"
                f"Folder: {folder}\n"
                f"Expected: {base_name}_cleaned.csv"
            )

        return pd.DataFrame()

    return pd.read_csv(path)


def load_current_performance():
    """
    Load the current student performance generated by
    performance_analysis.py.
    """

    path = (
        DATA_DIR
        / "analysis"
        / "powerbi"
        / "powerbi_student_performance.csv"
    )

    if not path.exists():

        raise FileNotFoundError(
            f"\nCurrent performance file not found:\n{path}"
        )

    df = pd.read_csv(path)

    required_columns = [
        "Student_ID",
        "Program_ID",
        "Program_Name",
        "Semester_ID",
        "Semester_Name",
        "Attendance_Percentage",
        "Assignment_Percentage",
        "Test_Percentage",
        "Overall_Performance_Score"
    ]

    missing = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing:

        raise ValueError(
            "\nMissing columns in current performance file:\n"
            f"{missing}"
        )

    return df


def get_semester_number(df):
    """
    Derive Semester_Number from Semester_Name.

    Example:
        Semester 1 -> 1
        Semester 3 -> 3

    No Semester_ID mapping is used.
    """

    if "Semester_Number" in df.columns:

        values = pd.to_numeric(
            df["Semester_Number"],
            errors="coerce"
        )

        if values.notna().any():

            return values

    if "Semester_Name" not in df.columns:

        raise ValueError(
            "Semester_Name is required to derive Semester_Number."
        )

    return pd.to_numeric(
        df["Semester_Name"]
        .astype(str)
        .str.extract(r"(\d+)", expand=False),
        errors="coerce"
    )


def normalize_attendance_status(df):
    """
    Standardize attendance status column.
    """

    df = df.copy()

    if df.empty:
        return df

    if "Attendance_Status" not in df.columns:

        if "Status" in df.columns:

            df["Attendance_Status"] = df["Status"]

        else:

            raise ValueError(
                "Attendance_Status/Status column not found."
            )

    df["Attendance_Status"] = (
        df["Attendance_Status"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    return df


# ============================================================
# CURRENT PERFORMANCE
# ============================================================

def prepare_current_performance():

    print("\nLoading current performance...")

    current = load_current_performance()

    current["Semester_Number"] = get_semester_number(
        current
    )

    current["Semester_Number"] = (
        current["Semester_Number"]
        .astype("Int64")
    )

    # --------------------------------------------------------
    # Keep only valid current semester records
    # --------------------------------------------------------

    current = current[
        current["Semester_Number"].notna()
    ].copy()

    # --------------------------------------------------------
    # Remove accidental duplicate student-semester records
    # --------------------------------------------------------

    current = (
        current
        .drop_duplicates(
            subset=[
                "Student_ID",
                "Semester_ID"
            ]
        )
        .copy()
    )

    print(
        f"Current performance records: {len(current)}"
    )

    return current


# ============================================================
# HISTORICAL SEMESTER 2
# ============================================================

def calculate_historical_sem2(current):

    print(
        "\nCalculating historical Semester 2..."
    )

    # --------------------------------------------------------
    # Load cleaned historical datasets
    # --------------------------------------------------------

    assignments = load_cleaned_csv(
        HISTORICAL_SEM2_DIR,
        "assignments",
        required=True
    )

    attendance = load_cleaned_csv(
        HISTORICAL_SEM2_DIR,
        "attendance",
        required=True
    )

    tests = load_cleaned_csv(
        HISTORICAL_SEM2_DIR,
        "tests",
        required=True
    )

    # Practical attendance is optional.
    # If available, it is included in attendance calculation.
    practical_attendance = load_cleaned_csv(
        HISTORICAL_SEM2_DIR,
        "practical_attendance",
        required=False
    )

    # --------------------------------------------------------
    # IMPORTANT
    #
    # We do NOT use historical Semester_ID values directly.
    #
    # The folder itself represents historical Semester 2.
    # Therefore every record inside this historical_sem2
    # dataset belongs to Semester 2.
    # --------------------------------------------------------

    # --------------------------------------------------------
    # Identify students who need historical Semester 2
    #
    # A student currently in a semester greater than 2
    # has already completed Semester 2.
    #
    # This avoids hard-coded Program_ID/Semester_ID mapping.
    # --------------------------------------------------------

    current_student_semester = (
        current[
            [
                "Student_ID",
                "Semester_Number"
            ]
        ]
        .drop_duplicates("Student_ID")
    )

    historical_student_ids = set(
        current_student_semester.loc[
            current_student_semester["Semester_Number"] > 2,
            "Student_ID"
        ]
        .astype(int)
        .tolist()
    )

    if not historical_student_ids:

        print(
            "No current students require historical Semester 2."
        )

        return pd.DataFrame()

    # --------------------------------------------------------
    # Filter historical datasets to required students
    # --------------------------------------------------------

    assignments = assignments[
        assignments["Student_ID"]
        .isin(historical_student_ids)
    ].copy()

    attendance = attendance[
        attendance["Student_ID"]
        .isin(historical_student_ids)
    ].copy()

    tests = tests[
        tests["Student_ID"]
        .isin(historical_student_ids)
    ].copy()

    if not practical_attendance.empty:

        practical_attendance = practical_attendance[
            practical_attendance["Student_ID"]
            .isin(historical_student_ids)
        ].copy()

    # --------------------------------------------------------
    # ATTENDANCE
    # --------------------------------------------------------

    attendance = normalize_attendance_status(
        attendance
    )

    attendance["Present"] = (
        attendance["Attendance_Status"]
        .eq("present")
        .astype(int)
    )

    attendance_parts = [
        attendance[
            [
                "Student_ID",
                "Present"
            ]
        ]
    ]

    # --------------------------------------------------------
    # Practical Attendance
    # --------------------------------------------------------

    if not practical_attendance.empty:

        practical_attendance = (
            normalize_attendance_status(
                practical_attendance
            )
        )

        practical_attendance["Present"] = (
            practical_attendance["Attendance_Status"]
            .eq("present")
            .astype(int)
        )

        attendance_parts.append(
            practical_attendance[
                [
                    "Student_ID",
                    "Present"
                ]
            ]
        )

    # --------------------------------------------------------
    # Combine regular + practical attendance
    # --------------------------------------------------------

    attendance_all = pd.concat(
        attendance_parts,
        ignore_index=True
    )

    attendance_student = (
        attendance_all
        .groupby("Student_ID")["Present"]
        .mean()
        .mul(100)
        .reset_index()
    )

    attendance_student.rename(
        columns={
            "Present": "Attendance_Percentage"
        },
        inplace=True
    )

    # --------------------------------------------------------
    # ASSIGNMENTS
    # --------------------------------------------------------

    assignments["Marks"] = pd.to_numeric(
        assignments["Marks"],
        errors="coerce"
    )

    assignments["Marks"] = (
        assignments["Marks"]
        .clip(
            lower=0,
            upper=ASSIGNMENT_MAX_MARKS
        )
    )

    assignment_student = (
        assignments
        .groupby("Student_ID")["Marks"]
        .mean()
        .div(ASSIGNMENT_MAX_MARKS)
        .mul(100)
        .reset_index()
    )

    assignment_student.rename(
        columns={
            "Marks": "Assignment_Percentage"
        },
        inplace=True
    )

    # --------------------------------------------------------
    # TESTS
    # --------------------------------------------------------

    tests["Marks"] = pd.to_numeric(
        tests["Marks"],
        errors="coerce"
    )

    tests["Marks"] = (
        tests["Marks"]
        .clip(
            lower=0,
            upper=TEST_MAX_MARKS
        )
    )

    test_student = (
        tests
        .groupby("Student_ID")["Marks"]
        .mean()
        .div(TEST_MAX_MARKS)
        .mul(100)
        .reset_index()
    )

    test_student.rename(
        columns={
            "Marks": "Test_Percentage"
        },
        inplace=True
    )

    # --------------------------------------------------------
    # COMBINE PERFORMANCE
    # --------------------------------------------------------

    result = attendance_student.merge(
        assignment_student,
        on="Student_ID",
        how="outer"
    )

    result = result.merge(
        test_student,
        on="Student_ID",
        how="outer"
    )

    # --------------------------------------------------------
    # OVERALL PERFORMANCE
    #
    # Attendance  = 30%
    # Assignment = 30%
    # Test       = 40%
    # --------------------------------------------------------

    result["Overall_Performance_Score"] = (
        result["Attendance_Percentage"]
        * ATTENDANCE_WEIGHT
        +
        result["Assignment_Percentage"]
        * ASSIGNMENT_WEIGHT
        +
        result["Test_Percentage"]
        * TEST_WEIGHT
    )

    # --------------------------------------------------------
    # PERFORMANCE CATEGORY
    # --------------------------------------------------------

    def category(score):

        if pd.isna(score):
            return "No Data"

        if score >= 80:
            return "Excellent"

        elif score >= 70:
            return "Good"

        elif score >= 50:
            return "Average"

        else:
            return "Poor"

    result["Performance_Category"] = (
        result["Overall_Performance_Score"]
        .apply(category)
    )

    # --------------------------------------------------------
    # STUDENT INFORMATION
    # --------------------------------------------------------

    student_columns = [
        "Student_ID",
        "Roll_No",
        "Name",
        "Department_ID",
        "Program_ID",
        "Program_Name"
    ]

    available_columns = [
        column
        for column in student_columns
        if column in current.columns
    ]

    student_info = (
        current[available_columns]
        .drop_duplicates("Student_ID")
        .copy()
    )

    result = result.merge(
        student_info,
        on="Student_ID",
        how="left"
    )

    # --------------------------------------------------------
    # HISTORICAL SEMESTER INFORMATION
    #
    # No database Semester_ID is exposed as Semester 2.
    # Semester 2 is represented semantically.
    # --------------------------------------------------------

    result["Semester_Number"] = 2

    result["Semester_Name"] = "Semester 2"

    # Historical Semester_ID is intentionally not taken
    # from current semester mapping.

    print(
        f"Historical Semester 2 records: {len(result)}"
    )

    return result


# ============================================================
# MAIN
# ============================================================

def main():

    print("\n======================================")
    print(" DASHBOARD 2 DATA PREPARATION")
    print("======================================\n")

    # --------------------------------------------------------
    # 1. CURRENT DATA
    # --------------------------------------------------------

    current = prepare_current_performance()

    # --------------------------------------------------------
    # 2. HISTORICAL SEMESTER 2
    # --------------------------------------------------------

    historical_sem2 = calculate_historical_sem2(
        current
    )

    # --------------------------------------------------------
    # 3. SELECT CURRENT DATA
    # --------------------------------------------------------

    current_columns = [
        "Student_ID",
        "Roll_No",
        "Name",
        "Department_ID",
        "Program_ID",
        "Program_Name",
        "Semester_ID",
        "Semester_Name",
        "Semester_Number",
        "Attendance_Percentage",
        "Assignment_Percentage",
        "Test_Percentage",
        "Overall_Performance_Score",
        "Performance_Category"
    ]

    current_dashboard = current[
        [
            column
            for column in current_columns
            if column in current.columns
        ]
    ].copy()

    # --------------------------------------------------------
    # 4. HISTORICAL DATA
    # --------------------------------------------------------

    historical_columns = [
        "Student_ID",
        "Roll_No",
        "Name",
        "Department_ID",
        "Program_ID",
        "Program_Name",
        "Semester_Number",
        "Semester_Name",
        "Attendance_Percentage",
        "Assignment_Percentage",
        "Test_Percentage",
        "Overall_Performance_Score",
        "Performance_Category"
    ]

    if not historical_sem2.empty:

        historical_dashboard = historical_sem2[
            [
                column
                for column in historical_columns
                if column in historical_sem2.columns
            ]
        ].copy()

        # ----------------------------------------------------
        # Keep Semester_ID separate from database IDs.
        #
        # Dashboard 2 needs semester stage, not a fake
        # database Semester_ID.
        # ----------------------------------------------------

        historical_dashboard["Semester_ID"] = pd.NA

    else:

        historical_dashboard = pd.DataFrame(
            columns=current_dashboard.columns
        )

    # --------------------------------------------------------
    # 5. COMBINE CURRENT + HISTORICAL
    # --------------------------------------------------------

    student_performance = pd.concat(
        [
            current_dashboard,
            historical_dashboard
        ],
        ignore_index=True
    )

    # --------------------------------------------------------
    # 6. REMOVE DUPLICATES
    # --------------------------------------------------------

    student_performance = (
        student_performance
        .drop_duplicates(
            subset=[
                "Student_ID",
                "Semester_Name"
            ]
        )
        .copy()
    )

    # --------------------------------------------------------
    # 7. ROUND PERFORMANCE VALUES
    # --------------------------------------------------------

    percentage_columns = [
        "Attendance_Percentage",
        "Assignment_Percentage",
        "Test_Percentage",
        "Overall_Performance_Score"
    ]

    for column in percentage_columns:

        if column in student_performance.columns:

            student_performance[column] = (
                pd.to_numeric(
                    student_performance[column],
                    errors="coerce"
                )
                .round(2)
            )

    # --------------------------------------------------------
    # 8. SORT STUDENT DATA
    # --------------------------------------------------------

    student_performance = (
        student_performance
        .sort_values(
            [
                "Program_ID",
                "Student_ID",
                "Semester_Number"
            ]
        )
        .reset_index(drop=True)
    )

    # --------------------------------------------------------
    # 9. SAVE STUDENT PERFORMANCE
    # --------------------------------------------------------

    student_output = (
        OUTPUT_DIR
        / "dashboard2_student_performance.csv"
    )

    student_performance.to_csv(
        student_output,
        index=False
    )

    # --------------------------------------------------------
    # 10. PROGRAM + SEMESTER SUMMARY
    # --------------------------------------------------------

    program_summary = (
        student_performance
        .groupby(
            [
                "Program_ID",
                "Program_Name",
                "Semester_Number",
                "Semester_Name"
            ],
            as_index=False
        )
        .agg(
            Total_Students=(
                "Student_ID",
                "nunique"
            ),

            Average_Attendance=(
                "Attendance_Percentage",
                "mean"
            ),

            Average_Assignment_Performance=(
                "Assignment_Percentage",
                "mean"
            ),

            Average_Test_Performance=(
                "Test_Percentage",
                "mean"
            ),

            Average_Overall_Performance=(
                "Overall_Performance_Score",
                "mean"
            )
        )
    )

    # --------------------------------------------------------
    # SORT
    # --------------------------------------------------------

    program_summary = (
        program_summary
        .sort_values(
            [
                "Program_ID",
                "Semester_Number"
            ]
        )
        .reset_index(drop=True)
    )

    # --------------------------------------------------------
    # ROUND SUMMARY VALUES
    # --------------------------------------------------------

    summary_columns = [
        "Average_Attendance",
        "Average_Assignment_Performance",
        "Average_Test_Performance",
        "Average_Overall_Performance"
    ]

    for column in summary_columns:

        program_summary[column] = (
            program_summary[column]
            .round(2)
        )

    # --------------------------------------------------------
    # 11. SAVE PROGRAM PERFORMANCE
    # --------------------------------------------------------

    program_output = (
        OUTPUT_DIR
        / "dashboard2_program_semester_performance.csv"
    )

    program_summary.to_csv(
        program_output,
        index=False
    )

    # --------------------------------------------------------
    # 12. PERFORMANCE CATEGORY SUMMARY
    # --------------------------------------------------------

    category_summary = (
        student_performance
        .groupby(
            [
                "Program_ID",
                "Program_Name",
                "Semester_Number",
                "Semester_Name",
                "Performance_Category"
            ],
            as_index=False
        )
        .agg(
            Student_Count=(
                "Student_ID",
                "nunique"
            )
        )
    )

    category_summary = (
        category_summary
        .sort_values(
            [
                "Program_ID",
                "Semester_Number",
                "Performance_Category"
            ]
        )
        .reset_index(drop=True)
    )

    category_output = (
        OUTPUT_DIR
        / "dashboard2_performance_categories.csv"
    )

    category_summary.to_csv(
        category_output,
        index=False
    )

    # --------------------------------------------------------
    # 13. DISPLAY FINAL RESULT
    # --------------------------------------------------------

    print(
        "\n======================================"
    )

    print(
        "FINAL PROGRAM / SEMESTER SUMMARY"
    )

    print(
        "======================================\n"
    )

    if program_summary.empty:

        print("No summary data available.")

    else:

        print(
            program_summary.to_string(
                index=False
            )
        )

    print(
        "\n======================================"
    )

    print(
        "FILES CREATED"
    )

    print(
        "======================================\n"
    )

    print(program_output)
    print(category_output)
    print(student_output)

    print(
        "\nDashboard 2 data preparation completed."
    )


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    main()